### ISSUE TITLE
Get a new logo

### ISSUE THREAD

**Issue by moul** [pathwar/assets#1]
cc @vikbez, @moul, @aimxhaisse

Requirements:
- not existing

Bonus:
- SVG
- Cool in color **and** in B&W

**Comment by moul** [comment]
cc @cerisier

**Comment by moul** [comment]
@vikbez can you post your drafts ?

**Comment by vikbez** [comment]
![](http://t.42k.fr/oaX6kt.png)
![](http://t.42k.fr/w5oaGY.png)
![](http://t.42k.fr/KtKoaa.png)
![](http://new.tinygrab.com/64d7d34f6588fe774e3085bd9b764fd4f9fd7ae11c.png)

**Comment by moul** [comment]
I like the idea :)

Can you also post your old tries with the `PW` letters ?

**Comment by vikbez** [comment]
it's at work, so tomorrow

**Comment by vikbez** [comment]
![](http://new.tinygrab.com/6fc1ddb357b48515810a9522427066beb475679286.png)

**Comment by vikbez** [comment]
![](http://new.tinygrab.com/6fc1ddb3579b5c99d0ffc853d7556afe6574f47440.png)

**Comment by vikbez** [comment]
![](http://new.tinygrab.com/6fc1ddb357e39cda604a63b04a15513d71e6846610.png)

**Comment by vikbez** [comment]
![](http://new.tinygrab.com/6fc1ddb357999f3cbb31edbef6ace7272132de3b24.png)
une bite.

**Comment by moul** [comment]
ahah

**Comment by moul** [comment]
I do prefer the pirate idea, I think you can already begin a more clean version, something very cartoon-like would be awesome

**Comment by vikbez** [comment]
![](http://www.cjoint.com/data/0AptONHTrCV_pathwarlogodraft1.jpg)

Like that ? (designer friend, we can ask for changes) (this is a draft, he can make an amazing colorful image from that) (he has da photoshop skillz)

**Comment by cerisier** [comment]
I like that.
Maybe without the flames, and once vectorized we can  simplify it and work
on the shades to make it look cartoonish !

**Comment by aimxhaisse** [comment]
:hamburger:

**Comment by moul** [comment]
yeah :+1: 

I also think it's too complicated and the fire is too much

**Comment by vikbez** [comment]
ben je trouve que ca dechire, effectivement il faudrait avoir les 2, vectoriel simplifié quand on a besoin de le mettre en petit,
et truc coloré qui-dechire pour quand on peut le mettre en grand
peut-etre rajouter un oeil dans une seule orbite pour faire lol

**Comment by moul** [comment]
:+1:

**Comment by Solvik** [comment]
looks like a wannabe pirate, love it
:+1:

**Comment by Kam3leoN** [comment]
http://img4.hostingpics.net/pics/427444capture.png

**Comment by Kam3leoN** [comment]
Hi!

Here is a more advanced version of the logo being created;)
The red color is not taken into account.
The logo is fully vectorized and create area under .psb to 900dpi -14k*14k pixel

Cheers ^^
Kam3leoN
<img src="http://img4.hostingpics.net/pics/427444capture.png" />

**Comment by moul** [comment]
:+1: for me, amazing stuff

**Comment by moul** [comment]
@everyone, what do you think ?
I think it's amazing for the V1 and enough to build up our identity

---

This kind of logo is very personal and we can easily create alternatives:
- black & white logo
- in a context with more details
- at the opposite, a very simple version near to the pixel art
- with clothes (so we can imagine a gentlemen skull)

---

If you guys are OK, we can ask @Kam3leoN to export his creation in some formats so we can put the logo everywhere (github orga / website / twitter)

**Comment by vikbez** [comment]
Woot woot !
:100:  :+1: :kiss: 

This rocks !

**Comment by aimxhaisse** [comment]
:ok_hand: :hamburger:

**Comment by Kam3leoN** [comment]
It is not finished yet in terms of end up.

And I also think about:
- A black and white version for such documents.
- A version with an opacity of 10% for funds letter.

Would you like the typography of the word "PathWar"?

Cheers!

**Comment by Solvik** [comment]
amazing :+1: :100:  \o/

**Comment by moul** [comment]
Yes, the typography is important too, maybe we will create another issue for that needs, with the first question : `pathwar`, `Pathwar`, `PATHWAR` or `PathWar` ? :)

**Comment by Kam3leoN** [comment]
<img src="http://img15.hostingpics.net/pics/190147Sanstitre1.png" />

<img src="http://img15.hostingpics.net/pics/955409Sanstitre2.png" />

**Comment by vikbez** [comment]
personnal thoughts: Text placement is great ! but maybe more visible (more white), and maybe another font (more computer-style) ?

**Comment by cerisier** [comment]
Yo, Looking awesome.
I'd rather keep the logo and the text separated.
Agree with vik's comment on the font.

**Comment by godric7** [comment]
:+1: :+1: :+1:

**Comment by moul** [comment]
Ok so let's go with this logo !

---

@Kam3leoN, I just invited you to a team on our organization with write access on this repository, you can accept the invitation on this page: https://github.com/pathwar/

Then, you will be able to push your files on the repository, I don't know if you already know how to push files on git yet, there is a help page on github: https://help.github.com/articles/set-up-git/ with one section per operating system (mac, windows, linux), we can also help you on the chat

---

I also invited you to our chat (check out your emails)

We will then create some dedicated issues for our needs (t-shirt version of the logo, stickers, etc)

We will need your postal address to send you the goodies we will create with your logos
and also need to know how you want to appear on our website in the "collaborator/about" page

**Comment by brmzkw** [comment]
awesome :)
