### ISSUE TITLE
QUESTION: pathwar, Pathwar, PATHWAR or PathWar ?

### ISSUE THREAD

**Issue by moul** [pathwar/assets#2]
Let's vote !
- **pathwar**: ******
- **Pathwar**: **
- **p47hw4r**: *
- **PATHWAR**: *
- **PathWar**: *
- **PathwaR**: 
- **Path War**: 
- **path-war**:

---

cc @aimxhaisse @Solvik @cerisier @blotus @mlequeux @vikbez

**Comment by moul** [comment]
Manfred: **pathwar** & **Pathwar**

**Comment by aimxhaisse** [comment]
mxs: pathwar

**Comment by cerisier** [comment]
Cerisier: pathwar

**Comment by mlequeux** [comment]
Martin: pathwar (ou pourquoi pas p47hw4r ;) )

**Comment by blotus** [comment]
Seb: Pathwar

**Comment by brmzkw** [comment]
pathwar or PATHWAR

**Comment by godric7** [comment]
pathwar

**Comment by Kam3leoN** [comment]
Kam3 : PatchWar

**Comment by Solvik** [comment]
pathwar

**Comment by cerisier** [comment]
Winner is pathwar.
@Kam3leoN : You can use pathwar from now on :smile:
