### ISSUE TITLE
QUESTION: slogan ?

### ISSUE THREAD

**Issue by moul** [pathwar/assets#3]
cc @mlequeux @cerisier @blotus @Solvik @aimxhaisse

**Comment by moul** [comment]
- **Pentest challenges, the cool way**
- **Let's hack !**
- **Learn to Hack**
- **Community Hack School**
- **Learn to Hack better, together.**
- **Social Hacking Platform.**

**Comment by cerisier** [comment]
Random batch of ideas :
- Hacker Training Program
- Become a hacker
- We will make you a hacker
- Learn Security, one level at a time
- Learn to hack, one level at a time
- We will teach you the dark side of the code (or force)
- We master the dark side. You will too.
- Learn to know the dark side of the code

I recommend the following great articles:
- https://medium.com/@ryangum/stop-using-made-simple-to-describe-your-startup-38d955f523af
- https://medium.com/lagniappe-spice/beyond-just-do-it-crafting-taglines-that-work-a1afc8b98b4e

I also recommend to have a look at http://www.producthunt.com/ and dive through other startups taglines.

**Comment by aimxhaisse** [comment]
- Dark side of the pown
- There is no spoon

(but it doesn't follow @cerisier 's articles :D)

Edit:
- Learn to hack, the fun way
- Learn to hack from scratch

**Comment by aimxhaisse** [comment]
* Learn to hack, the fun way

**Comment by moul** [comment]
- Play, Hack & Learn to be secure

**Comment by godric7** [comment]
I just really like the word "pwn":
- pwn-enabled CTF.
- there is no spwn
- pwn republic.
- feel the pwn
- fear the pwn
- (the) pwn stories.
- pwn HARD.
- the facebook of pwn
- the brazzer of pwn
- there is no spwn

**Comment by Kam3leoN** [comment]
I like the idea of star wars ^^
- Mastered the dark side of the code.

join the pirate side to the dark side is a good idea..

**Comment by aimxhaisse** [comment]
there is no spwn :hamburger:
